---
# tasks file for ec2_build
- name: Create EC2 security group
  ec2_group:
    name: builder_sg
    description: Builder ec2 security group
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: ec2_sec

- name: Create key pair
  ec2_key:
    name: aws
    region: us-east-1
  register: ec2_key

- name: Save private key
  copy: content="{{ ec2_key.key.private_key }}" dest=".ssh/id_rsa" mode=0600
  when: ec2_key.changed

- name: create aws instance
  ec2:
    key_name: aws
    region: us-east-1
    group: builder_sg
    instance_type: t2.micro
    image: ami-08c40ec9ead489470
    wait: yes
    count: 1
#    assign_public_ip: yes
  register: output
  
- name: print
  debug:
    ip_build: output.instances[0].public_ip

- name: update inventory
  add_host:
    name: "{{ ip_build }}"
    groups: "{{ group_builds }}"

- amazon.aws.s3_bucket:
    name: "{{ buck }}"
    state: present