---
# tasks file for ec2_web
- name: Create EC2 security group
  ec2_group:
    name: web_sg
    description: Webserver ec2 security group
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp 
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: ec2_sec

- name: Create key pair
  ec2_key:
    name: aws
    region: us-east-1
  register: ec2_key

- name: Save private key
  copy: content="{{ ec2_key.key.private_key }}" dest=".ssh/id_rsa" mode=0600
  when: ec2_key.changed

- name: create aws instance
  ec2:
    key_name: aws
    region: us-east-1
    group: web_sg
    instance_type: t2.micro
    image: ami-08c40ec9ead489470
    wait: yes
    count: 1
  register: output
  
- name: print
  debug:
    var: output.instances[1].public_ip

- name: update inventory
  add_host:
    name: "{{ output.instances[1].public_ip }}"
    groups: "{{ group_web }}"